name: AKSToolSet-v2.$(date:yy)$(DayOfYear).$(rev:r)-$(Build.SourceBranchName)
trigger:
- master
- issue*
workspace:
    clean: true
pr:
- master

pool:
  vmImage: macOS-latest
  demands: npm

steps:
- task: VersionExtractor@4
  name: versionExtractor
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(build.buildNumber)'

- task: TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: Npm@1
  displayName: TypeScript Install
  inputs:
    command: 'custom'
    workingDir: 'KubectlGetServiceIp'
    customCommand: 'install -g typescript' 

- task: Npm@1
  displayName: 'Build KubectlGetServiceIp'
  inputs:
    command: 'custom'
    workingDir: KubectlGetServiceIp
    customCommand: 'run publishExt'
    verbose: false

- task: Npm@1
  displayName: 'Build KubectlGetServiceSelector'
  inputs:
    command: 'custom'
    workingDir: KubectlGetServiceSelector
    customCommand: 'run publishExt'
    verbose: false

- task: PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    extensionVersion: '$(versionExtractor.fullVersion)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

