name: AKSToolSet-v1.$(date:yyyy)$(DayOfYear).$(rev:r)-$(Build.SourceBranchName)
trigger:
- master
- issue*
workspace:
    clean: all
pr:
- master

pool:
  name: MacNetCorePools
  demands: npm

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: ExpertaPreview.pvprExpertaDevOpsTools.custom-build-release-task.VersionExtractor@4
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(build.buildNumber)'

- task: Npm@1
  displayName: 'npm install KubectlGetServiceIp'
  inputs:
    workingDir: KubectlGetServiceIp
    verbose: false

- task: Npm@1
  displayName: 'npm install KubectlGetServiceSelector'
  inputs:
    workingDir: KubectlGetServiceSelector
    verbose: false

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    extensionVersion: '$(versionExtractor.fullVersion)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

